WORKSHEET_STATUS_PENDING = 'PENDING'
WORKSHEET_STATUS_UNRELEASED = 'UNRELEASED'
WORKSHEET_STATUS_RELEASED = 'RELEASED'

WORKSHEET_STATUS_CHOICES = (
    (WORKSHEET_STATUS_PENDING, 'Pending'),
    (WORKSHEET_STATUS_UNRELEASED, 'Unreleased'),
    (WORKSHEET_STATUS_RELEASED, 'Released'),
)
