from ComSemApp.BERT.bert_model import BERTModel

WORKSHEET_STATUS_PENDING = 'PENDING'
WORKSHEET_STATUS_UNRELEASED = 'UNRELEASED'
WORKSHEET_STATUS_RELEASED = 'RELEASED'
WORKSHEET_STATUS_PROCESSING = 'PROCESSING'
WORKSHEET_STATUS_REVIEW = 'REVIEW'

WORKSHEET_STATUS_CHOICES = (
    (WORKSHEET_STATUS_PENDING, 'Pending'),
    (WORKSHEET_STATUS_UNRELEASED, 'Unreleased'),
    (WORKSHEET_STATUS_RELEASED, 'Released'),
    (WORKSHEET_STATUS_PROCESSING, 'Processing'),
    (WORKSHEET_STATUS_REVIEW, 'Review'),
)

BERT_MODEL = BERTModel()