# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ComSemApp.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachinginstance',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ComSemApp.Teacher'),
            preserve_default=False,
        ),
    ]
