# Generated by Django 2.0 on 2018-03-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='frequency',
        ),
    ]
