# Generated by Django 2.0 on 2018-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0002_remove_tag_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='all_do',
            field=models.BooleanField(default=False),
        ),
    ]
