# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0002_auto_20171126_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teachinginstance',
            name='user',
        ),
    ]
