# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0003_auto_20171126_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
