# Generated by Django 2.0 on 2018-07-28 15:45

from django.db import migrations, models
import django.db.models.deletion

from ComSemApp.teacher.constants import WORKSHEET_STATUS_UNRELEASED, WORKSHEET_STATUS_RELEASED

class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0003_expression_all_do'),
    ]

    def convert_released_to_status(apps, schema_editor):
        Worksheet = apps.get_model("ComSemApp", "Worksheet")
        worksheets = Worksheet.objects.all()
        for worksheet in worksheets:
            released = worksheet.released
            worksheet.status = WORKSHEET_STATUS_RELEASED if released else WORKSHEET_STATUS_UNRELEASED
            worksheet.save()

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNRELEASED', 'Unreleased'), ('RELEASED', 'Released')], default='PENDING', max_length=10),
        ),
        migrations.RunPython(convert_released_to_status, reverse_func),
        migrations.AlterField(
            model_name='worksheet',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='ComSemApp.Course'),
        ),
    ]
