# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0004_course_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
