# Generated by Django 2.0 on 2018-07-28 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0005_auto_20180728_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ComSemApp.Topic'),
        ),
    ]
