# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0006_auto_20171129_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ComSemApp.Student'),
        ),
    ]
