# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0007_expression_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expression',
            name='enrollment',
        ),
    ]
