# Generated by Django 2.0 on 2018-07-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0008_auto_20180728_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheet',
            old_name='topic_char_field',
            new_name='topic',
        ),
    ]
