# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0009_remove_expression_all_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ComSemApp.Student'),
        ),
    ]
