# Generated by Django 2.0 on 2018-08-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0009_auto_20180728_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('ungraded', 'ungraded'), ('complete', 'complete'), ('incomplete', 'incomplete')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='worksheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ComSemApp.Worksheet'),
        ),
    ]
