# Generated by Django 2.0 on 2017-12-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0010_auto_20171129_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequentialwords',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ComSemApp.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ComSemApp.Tag'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ComSemApp.Topic'),
        ),
    ]
