# Generated by Django 2.0 on 2018-08-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0010_auto_20180825_0811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattempt',
            unique_together={('student_submission', 'expression')},
        ),
    ]
