# Generated by Django 2.0 on 2017-12-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0011_auto_20171204_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='reformulation_audio',
            field=models.FileField(upload_to=''),
        ),
    ]
