# Generated by Django 2.0 on 2018-09-08 15:47

import ComSemApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0012_auto_20180826_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expression',
            name='reformulation_audio',
        ),
        migrations.AddField(
            model_name='expression',
            name='audio',
            field=models.FileField(null=True, upload_to=ComSemApp.models.audio_directory_path),
        ),
    ]
