# Generated by Django 2.0 on 2017-12-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0012_auto_20171204_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='reformulation_audio',
            field=models.FileField(upload_to='efs/ExpressionReformulations'),
        ),
    ]
