# Generated by Django 2.0.12 on 2019-11-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0013_auto_20180929_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('correct', models.BooleanField(default=None)),
                ('response_time', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComSemApp.Course')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComSemApp.Expression')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ComSemApp.Student')),
            ],
            options={
                'verbose_name': 'Review Attempt',
            },
        ),
    ]
