# Generated by Django 2.0.12 on 2020-04-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0013_auto_20180929_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattempt',
            name='error_type',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
