# Generated by Django 2.0.12 on 2020-05-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0014_auto_20200501_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattempt',
            old_name='correct',
            new_name='text_correct',
        ),
    ]
