# Generated by Django 2.2 on 2021-11-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0015_auto_20200503_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='run_through_model',
            field=models.BooleanField(default=False),
        ),
    ]
