# Generated by Django 2.2 on 2020-11-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0014_studentattempt_error_type'),
        ('ComSemApp', '0015_auto_20200503_1240'),
    ]

    operations = [
    ]
