# Generated by Django 3.1.7 on 2021-04-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0015_auto_20200503_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='worksheet',
            options={},
        ),
    ]
