# Generated by Django 2.2 on 2021-02-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0015_auto_20200503_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattempt',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
