# Generated by Django 2.2 on 2021-03-10 20:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0015_auto_20200503_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=255)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComSemApp.ErrorCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('end_index', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComSemApp.ErrorCategory')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComSemApp.Expression')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComSemApp.ErrorSubcategory')),
            ],
        ),
    ]
