# Generated by Django 2.2 on 2021-11-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0016_worksheet_run_through_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNRELEASED', 'Unreleased'), ('RELEASED', 'Released'), ('PROCESSING', 'Processing')], default='PENDING', max_length=10),
        ),
    ]
