# Generated by Django 2.2 on 2021-03-11 00:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0016_errorcategory_errorsubcategory_expressionerrors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressionerrors',
            name='end_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expressionerrors',
            name='start_index',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='expressionerrors',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ComSemApp.ErrorSubcategory'),
        ),
    ]
