# Generated by Django 3.1.7 on 2021-04-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0016_auto_20210403_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattempt',
            name='audio_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='text_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
