# Generated by Django 2.0 on 2017-12-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0016_auto_20171206_1603'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='sessiontype',
            order_with_respect_to=None,
        ),
    ]
