# Generated by Django 2.2 on 2022-02-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0017_auto_20211109_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='error_tag',
            field=models.CharField(choices=[('SV agr', 'Subject Verb Agreement'), ('NP', 'Noun phrase'), ('TSeq', 'Tense Sequence'), ('SVC', 'Subject-verb-complement')], default='NP', max_length=6),
        ),
        migrations.AddField(
            model_name='expression',
            name='hint_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expression',
            name='include_on_worksheet',
            field=models.BooleanField(default=True),
        ),
    ]
