# Generated by Django 2.0 on 2017-12-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0018_coursetype_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachinginstance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teachinginstance',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(to='ComSemApp.Teacher'),
        ),
        migrations.DeleteModel(
            name='TeachingInstance',
        ),
    ]
