# Generated by Django 2.2 on 2022-01-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0018_auto_20220131_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressionerrors',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
