# Generated by Django 2.2 on 2022-09-16 18:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ComSemApp', '0020_expressionerrors_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpressionErrors',
            new_name='ExpressionError',
        ),
        migrations.AlterModelOptions(
            name='errorcategory',
            options={'verbose_name_plural': 'error categories'},
        ),
        migrations.AlterModelOptions(
            name='errorsubcategory',
            options={'verbose_name_plural': 'error subcategories'},
        ),
    ]
