# Generated by Django 2.0 on 2017-12-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0020_auto_20171208_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
