# Generated by Django 2.2 on 2022-02-22 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0018_auto_20220201_0110'),
        ('ComSemApp', '0020_expressionerrors_user'),
    ]

    operations = [
    ]
