# Generated by Django 3.2 on 2022-09-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0020_expressionerrors_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattempt',
            name='audio_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='text_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
