# Generated by Django 3.1.7 on 2022-02-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0020_expressionerrors_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='worksheet',
            options={},
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='audio_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='text_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
