# Generated by Django 3.2 on 2022-09-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0021_auto_20220916_1818'),
        ('ComSemApp', '0021_auto_20220916_2047'),
    ]

    operations = [
    ]
