# Generated by Django 2.2 on 2022-03-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0021_merge_20220222_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='hint_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expression',
            name='hint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
