# Generated by Django 3.2 on 2023-04-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0022_merge_0021_auto_20220916_1818_0021_auto_20220916_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='youglish_query',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
