# Generated by Django 2.2 on 2022-04-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0022_auto_20220303_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='error_tag',
            field=models.CharField(choices=[('NP', 'Noun Phrase'), ('VP', 'Verb Phrase'), ('AjP', 'Adjective Phrase'), ('AvP', 'Adverb Phrase'), ('PP', 'Preposition Phrase'), ('Pco', 'Pco'), ('Complex', 'Complex'), ('SVC', 'Subject-Verb-Completer'), ('Adjunct', 'Adjunct'), ('Complementation', 'Complementation'), ('TR', 'Tranistive'), ('OTR', 'Intransitive'), ('LINK', 'Linking'), ('Voice', 'Voice (Passive/Active)'), ('Question', 'Question'), ('Negative', 'Negative'), ('modal', 'Modal Auxiliary'), ('Exist', 'Existence'), ('SS', 'SS'), ('CLn', 'Noun Clause'), ('CLaj', 'Adjective Clause'), ('CLav', 'Adverb Clause'), ('CLco', 'Coordinated Clauses'), ('SB', 'SB'), ('OTimed', 'Unitimed verb phrase'), ('TSeq', 'Tense Sequence'), ('PnSeq', 'Pronoun Sequence'), ('NSeq', 'Noun Sequence'), ('DSeq', 'Determiner Sequence'), ('Collocation', 'Collocation'), ('Predication', 'Predication'), ('Grammar Ideas', 'Grammar Ideas'), ('Miscellaneous', 'Miscellaneous'), ('V+C', 'Verb and Completer'), ('Parallelism', 'Parallelism'), ('apposition', 'Apposition'), ('wf', 'Word Form'), ('Word choice', 'Word Choice'), ('idiom', 'Idiom'), ('Verb complement', 'Complementation'), ('Svconcord', 'Subject-Verb Agreement'), ('semantics', 'Semantics'), ('SV agr', 'Svconcord'), ('word order', 'Word Order'), ('pronoun', 'Pronoun'), ('Timed', 'Timed verb phrase'), ('CLwh', 'Wh- Clause'), ('Completer', 'Completer'), ('Connector', 'Clco'), ('Comparatives', 'Comparatives'), ('Nomseq', 'Nomseq')], default='NP', max_length=6),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNRELEASED', 'Unreleased'), ('RELEASED', 'Released'), ('PROCESSING', 'Processing'), ('REVIEW', 'Review')], default='PENDING', max_length=10),
        ),
    ]
