# Generated by Django 3.2 on 2022-11-22 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0022_merge_0021_auto_20220916_1818_0021_auto_20220916_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingPracticeAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('correct', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Correctness Score')),
                ('wpm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Words per Minute')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComSemApp.expression')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ComSemApp.student')),
            ],
            options={
                'verbose_name': 'Speaking Practice Attempt',
            },
        ),
    ]
