# Generated by Django 2.0 on 2017-12-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0022_auto_20171208_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
    ]
