# Generated by Django 2.0 on 2017-12-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0023_auto_20171209_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='ComSemApp.Student'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ComSemApp.Student'),
            preserve_default=False,
        ),
    ]
