# Generated by Django 2.0 on 2017-12-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0024_auto_20171211_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='enrollment',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
