# Generated by Django 2.0 on 2017-12-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0025_auto_20171211_1419'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('form', 'tag')},
        ),
    ]
