# Generated by Django 3.2 on 2023-03-21 02:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0026_transcribe_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingPracticeAttemptReviewRequest',
            fields=[
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComSemApp.speakingpracticeattempt')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instructor Review Request for Speaking Practice Attempt',
            },
        ),
        migrations.CreateModel(
            name='SpeakingPracticeAttemptReview',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComSemApp.speakingpracticeattemptreviewrequest')),
                ('date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Teacher Comments')),
                ('original_score', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Original Score')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ComSemApp.teacher')),
            ],
            options={
                'verbose_name': 'Speaking Practice Attempt Review',
            },
        ),
    ]
