# Generated by Django 2.0 on 2017-12-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0026_auto_20171211_1421'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='worksheet',
            order_with_respect_to='course',
        ),
    ]
