# Generated by Django 3.2 on 2023-05-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0023_expression_youglish_query'),
        ('ComSemApp', '0027_generate_sessions'),
        ('ComSemApp', '0027_speakingpracticeattemptreview_speakingpracticeattemptreviewrequest'),
    ]

    operations = [
    ]
