# Generated by Django 2.0 on 2017-12-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0027_auto_20171211_1530'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='course',
            order_with_respect_to='session',
        ),
        migrations.AlterOrderWithRespectTo(
            name='session',
            order_with_respect_to='start_date',
        ),
    ]
