# Generated by Django 2.0 on 2017-12-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0028_auto_20171211_1531'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='worksheet',
            order_with_respect_to='date',
        ),
    ]
