# Generated by Django 2.0 on 2017-12-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0029_auto_20171211_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='studentsubmission',
            options={'get_latest_by': 'date', 'verbose_name': 'Student Submission'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='session',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='worksheet',
            order_with_respect_to='course',
        ),
    ]
