# Generated by Django 2.0 on 2017-12-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0030_auto_20171211_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-session__start_date',)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('user__last_name', 'user__first_name')},
        ),
        migrations.AlterModelOptions(
            name='worksheet',
            options={'ordering': ['-date']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='course',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='worksheet',
            order_with_respect_to=None,
        ),
    ]
