# Generated by Django 2.0 on 2018-01-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0031_auto_20171212_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattempt',
            name='correct',
            field=models.NullBooleanField(default=None),
        ),
    ]
