# Generated by Django 2.0 on 2018-01-15 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComSemApp', '0032_auto_20180106_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksheet',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComSemApp.Student'),
        ),
    ]
